### ISSUE TITLE
Allow for students with no classes

### ISSUE THREAD

**Issue by jhowe-dev** [jhowe-dev/475Project#11]
^^

**Comment by vqn1204** [comment]
Main thing is to remove the requirements in add-student-controller and edit-student-controller (or change it to require just name/ID of student). However, when the submit button is pressed after requirements are met, it will now jump to "failed to add." Unsure what else needs to be updated to fix this.

**Comment by vqn1204** [comment]
In firebase-service.js, when attempting to add a student without a schedule, code does not reach line 54/55 and fails at that function(snapshot).

**Comment by vqn1204** [comment]
Got access to the firebase rules, may have to change those to allow student with no classes.

**Comment by pranjalsingi** [comment]
Finally working..!
