### ISSUE TITLE
Fix accidental candidacy bug

### ISSUE THREAD

**Issue by jhowe-dev** [jhowe-dev/475Project#7]
Sometimes students are listed as candidates when they shouldn't.  This
happened when student has less than or equal to 15 minites between his class
and the assigned class.  When assigned class ends at the same time that 
student's class begins, student is still lsted as a candidate

**Comment by TheUnCola** [comment]
Seems as if the base candidacy functionality isn't being called at all. I'm still working on tracing the code to find out what the issue is. This also ties into the horrible wait time bug.
